### PR TITLE
Suggestions for Ch. 4 (Estimation)

### PR DESCRIPTION
**Pull request by mayamathur**
I made some suggestions about the structure for Chapter 4. I tried to be a little extra detailed in my commits to explain my thinking. Probably makes sense to discuss in real time your thoughts on this?

### CODE REVIEW

**Comment by mcfrank** [comment]
hi! thanks for this!  can you remove the conflicting files from the PR? (leave just the Rmd)

**Comment by mayamathur** [comment]
Sure – try this now?

**Comment by mcfrank** [comment]
sorry to be slow, looks like you may have rendered because there are conflicts on all the html now?

**Comment by mayamathur** [comment]
Sorry! Will look at this next week.

On Fri, Sep 17, 2021 at 11:34 AM Michael Frank ***@***.***>
wrote:

> sorry to be slow, looks like you may have rendered because there are
> conflicts on all the html now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/d4dd5512852383eb4826a8c8d18e5f843696e67e?url=https%3A%2F%2Fgithub.com%2Flangcog%2Fexperimentology%2Fpull%2F18%23issuecomment-922000603&userId=6925957&signature=0c9566ab15ae1f44>,
> or unsubscribe
> <https://mailtrack.io/trace/link/f685488403d9a2935fb80570929b0e467d94c92a?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEE6HR2T7IL77DSBWAB3N3UCOC27ANCNFSM5EAY76JA&userId=6925957&signature=e1be2c89fe43ea24>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://mailtrack.io/trace/link/7df4ceaf0d1f66d01b1a8bbeb4e045e34f18958f?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&userId=6925957&signature=6cbcbdd22356d4e1>
> or Android
> <https://mailtrack.io/trace/link/4316f99d40f15c9afc7a5cda2fd91d6ffb6285ee?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&userId=6925957&signature=c5f9efe03fd36467>.
>
>


-- 
Maya Mathur
Assistant Professor, Quantitative Sciences Unit
<https://mailtrack.io/trace/link/960a7fe53b338a6a560e18a1d800c944dfcc206b?url=https%3A%2F%2Fmed.stanford.edu%2Fqsu.html&userId=6925957&signature=1deaf60213624776>
Associate Director, Center for Open and Reproducible Science
<https://mailtrack.io/trace/link/a8a149545a385f88cb261559e7d7287c6a3fd2ad?url=https%3A%2F%2Fdatascience.stanford.edu%2Fcores&userId=6925957&signature=9912bbebb7a1629f>
Stanford University
Website
<https://mailtrack.io/trace/link/fa4608f6052ce7a2ffab896d888cdcd338435bf8?url=http%3A%2F%2Fwww.mayamathur.com&userId=6925957&signature=ae3c0d66c530a9ae>

<https://mailtrack.io/trace/link/85ac81327a156f0a51ea5b019755ff3ae25e3713?url=https%3A%2F%2Fmed.stanford.edu%2Fprofiles%2Fmaya-mathur&userId=6925957&signature=6795d5af7c3dbc02>

**Comment by mcfrank** [comment]
integrating by hand. :)

**Comment by mayamathur** [comment]
Sorry!

On Tue, Sep 21, 2021 at 9:26 AM Michael Frank ***@***.***>
wrote:

> integrating by hand. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/a0bb32875e64b757d349ef930d543fe3214b5b7a?url=https%3A%2F%2Fgithub.com%2Flangcog%2Fexperimentology%2Fpull%2F18%23issuecomment-924150730&userId=6925957&signature=1f6dd41bca68a8fd>,
> or unsubscribe
> <https://mailtrack.io/trace/link/3b2833e6eace1089db6926cab641c6c3bcbcb0b3?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEE6HQH3SG7RXDKSYP3EHLUDCW3PANCNFSM5EAY76JA&userId=6925957&signature=d7451531adf2637c>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://mailtrack.io/trace/link/2d692916bf8ded7eb1cae2e79a93cccd2f604e2b?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&userId=6925957&signature=5f490b4a94b97fc1>
> or Android
> <https://mailtrack.io/trace/link/964c847e5298d75853a848139c67a426362f9e21?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&userId=6925957&signature=a17aeddec358d37f>.
>
>


-- 
Maya Mathur
Assistant Professor, Quantitative Sciences Unit
<https://mailtrack.io/trace/link/5dc1f3380aaa0aa83c62c63ad4a9066d2a31f32d?url=https%3A%2F%2Fmed.stanford.edu%2Fqsu.html&userId=6925957&signature=c274abcd2a6d19f3>
Associate Director, Center for Open and Reproducible Science
<https://mailtrack.io/trace/link/f30a3ba7b4bf1eb08f2ff598e2d0b89c3325295a?url=https%3A%2F%2Fdatascience.stanford.edu%2Fcores&userId=6925957&signature=593af5e039085da2>
Stanford University
Website
<https://mailtrack.io/trace/link/2eb9c3fd03b687a5dc1f05cd1c9e6e8ed4c14466?url=http%3A%2F%2Fwww.mayamathur.com&userId=6925957&signature=930687cc9dcf720e>

<https://mailtrack.io/trace/link/954a48acce934af00a3d4ee9979b78a42fadb719?url=https%3A%2F%2Fmed.stanford.edu%2Fprofiles%2Fmaya-mathur&userId=6925957&signature=e2d1dff180cb60c3>

**Pull request closed without merging**
